import 'dotenv/config';

export default {
    PORT: process.env.PORT,
    SUPABASE_CONNECTION_STRING: process.env.SUPABASE_CONNECTION_STRING,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    NOMBA_MAIN_ACCOUNT_ID: process.env.NOMBA_MAIN_ACCOUNT_ID,
    NOMBA_SUB_ACCOUNT_ID: process.env.NOMBA_SUB_ACCOUNT_ID,
    NOMBA_LIVE_CLIENT_ID: process.env.NOMBA_LIVE_CLIENT_ID,
    NOMBA_LIVE_SECRET_KEY: process.env.NOMBA_LIVE_SECRET_KEY,
    NOMBA_TEST_CLIENT_ID: process.env.NOMBA_TEST_CLIENT_ID,
    NOMBA_TEST_SECRET_KEY: process.env.NOMBA_TEST_SECRET_KEY,
    NOMBA_API_URL: process.env.NOMBA_API_URL,
    NOMBA_WEBHOOK_SIGNATURE: process.env.NOMBA_WEBHOOK_SIGNATURE
}